### ISSUE TITLE
an iterable that is a list of sublists behaves differently from multiprocessing.pool.Pool

### ISSUE THREAD

**Issue by bernstei** [Helveg/zwembad#7] opened 2021-03-05 21:36 UTC
[Sorry, just realized this isn't a direct fork of mpipool.  Feel free to ignore this issue while I figure out if my problem is still relevant.  If it's not, I'll close the issue.  If it is, I'll re-edit this message]

I'd like to use `mpipool.Pool` as much as a drop-in replacement for `multiprocessing.pool.Pool` as possible. Unfortunately, if the iterable is a list of lists the two implementations behave differently.   

[mpipool_vs_multiprocessing_pool_list_of_lists.txt](https://github.com/Helveg/zwembad/files/6093505/mpipool_vs_multiprocessing_pool_list_of_lists.txt)

Without mpirun it uses multiprocessing, and the output is
```
> python mpipool_vs_multiprocessing_pool_list_of_lists.txt
using multiprocessing.pool.Pool
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
op len(args) 1
```

with mpirun it uses mpipool and the output is
```
> mpirun -np 4 mpipool_vs_multiprocessing_pool_list_of_lists.txt
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
op len(args) 10
```

Looks like the difference between calling `op(args)` and `op(*args)`.

**Comment by Helveg** [comment] 2021-03-06 11:19
Yea, it's because the original mpipool's map behaves incorrectly, it is fixed with this package though, is it not? But I couldn't continue it under the same name on PyPI :/ I could see if I can dispute it as an abandoned package (opened #8).

I rewrote the package to behave according to the [`concurrent.futures.Executor`'s](https://docs.python.org/3/library/concurrent.futures.html) interface. Is that compatible with the `multiprocessing.pool.Pool` interface? If not I can probably create another class that is compatible with it for you.

**Comment by Helveg** [comment] 2021-03-06 11:20
See also https://gitlab.com/uweschmitt/mpipool/-/issues/4 and my fix https://gitlab.com/uweschmitt/mpipool/-/merge_requests/1

On this repo it was fixed with https://github.com/Helveg/zwembad/pull/1

**Comment by bernstei** [comment] 2021-03-06 14:50
Great, thanks.  I'll check it out early next week.

**Comment by bernstei** [comment] 2021-03-08 14:16
OK - I'm having issues, which I'm guessing are python version related.  What's the minimum python version you plan to support?  3.6 is fairly commonly installed on change-averse HPC centers.
```
>>> import zwembad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cluster2/bernstei/.local/lib/python3.6/site-packages/zwembad/__init__.py", line 4, in <module>
    from .pool import MPIPoolExecutor
  File "/home/cluster2/bernstei/.local/lib/python3.6/site-packages/zwembad/pool.py", line 87
    def submit(self, fn, /, *args, **kwargs):
```

**Comment by Helveg** [comment] 2021-03-08 14:41
Aha, yes that could be the `/` in the function signature, I think that's 3.7+.

You can just remove that and things will work just as well! I included it for compatibility with [this interface](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.submit) I'm not sure if the rest of the code will launch on 3.6 though, 3.6 was released 4 years ago :s

**Comment by bernstei** [comment] 2021-03-08 14:48
Would you be willing to support an alternate version of that interface (testing on python version support for that syntax), so I don't have to fork it?

**Comment by Helveg** [comment] 2021-03-08 14:57
I could just quickly release a dev version for you and you can install that, then when your HPC upgrades you can switch over to newer versions. There's been some good news though, the original author has reached out and I will be able to continue this project as `mpipool` in the future :) There is some work to be done though but stay tuned.

I'm testing out the package for you on 3.6 and will release the dev version for you in let's say 20 min! (if all goes well)

**Comment by bernstei** [comment] 2021-03-08 15:08
Looks like the 3.6 version of queue does not have SimpleQueue, either, so getting support for earlier versions may be a bit more involved.

**Comment by Helveg** [comment] 2021-03-08 15:15
I got it working on 3.6! Use `pip install zwembad==1.2.0dev0` :)

**Comment by bernstei** [comment] 2021-03-08 15:55
Looks like it only sort of works.   I'm using nearly
 the same code as uploaded above [zwembad_vs_multiprocessing_pool_list_of_lists.txt](https://github.com/Helveg/zwembad/files/6102523/zwembad_vs_multiprocessing_pool_list_of_lists.txt)
except for doing `from zwembad import MPIPoolExecutor as Pool` and adding `p.workers_exit()`.  It runs, although only tasks with mpi rank > 0 actually seem to do anything, and it gives 3 copies of this error message when it ends
```
Traceback (most recent call last):
  File "mpipool_vs_multiprocessing_pool_list_of_lists.py", line 30, in <module>
    p.workers_exit()
  File "/home/cluster2/bernstei/.local/lib/python3.6/site-packages/zwembad/pool.py", line 197, in workers_exit
    raise RuntimeError("Worker threads should have been handed exit object")
RuntimeError: Worker threads should have been handed exit object
```

**Comment by bernstei** [comment] 2021-03-08 16:00
OK, I see, it's the lack of with `with Pool() as pool:`.  I guess the worker threads aren't getting closed properly?  Is there a way to trigger than manually?  I'm grafting this onto a complex command line script, so wrapping all the actual work in a "with" clause is not convenient.

**Comment by Helveg** [comment] 2021-03-08 16:10
Ok, so the previous package would keep the workers in an eternal loop of working when you did `pool = Pool()`, even after the pool had closed, and the rest of the code would only be executed by the master.

I fixed this and had the workers rejoin the code after the pool has closed, but that does imply that you will have to "fence" off the pieces of the code that the workers are not supposed to execute. The proper idiom for it is:

```python
with Pool() as pool:
  pool.workers_exit()
  # Rest of the code only the master does
```

But you can also use the `pool.is_worker()` function and do it without any `with` statements:

```python
pool = Pool()
if pool.is_master():
  # Do everything
else:
  # Most likely do nothing

**Comment by bernstei** [comment] 2021-03-08 16:20
Hmm - this is still giving the same error.  Are you sure there isn't something else I need to do to reproduce the __exit__ which is triggered by the context manager when you do "with Pool() as pool"
```
    from zwembad import MPIPoolExecutor as Pool
    p = Pool()
    if p.is_worker():
        p.workers_exit()

    l = list(range(100))

    r = p.map(op, _grouper(10, l))
    p.shutdown()
```

**Comment by Helveg** [comment] 2021-03-08 16:24
Oh right, I see the issue now, I'll add a fix, but the code should be:

```python
    from zwembad import MPIPoolExecutor as Pool
    p = Pool()
    if p.is_master():
      l = list(range(100))
      r = p.map(op, _grouper(10, l))
      p.shutdown()
```

That does wrap all the master code again, so if you need only 1 pool maybe something like this would work for you?

```python
    from zwembad import MPIPoolExecutor as Pool
    p = Pool()
    if p.is_worker():
      exit()
    l = list(range(100))
    r = p.map(op, _grouper(10, l))
    p.shutdown()
```

Like before though, the workers will only survive 1 pool and all subsequent code is master only

**Comment by bernstei** [comment] 2021-03-08 16:28
> Oh right, I see the issue now, I'll add a fix, but the code should be:
> That does wrap all the master code again, so if you need only 1 pool maybe something like this would work for you?
> 
> ```python
>     from zwembad import MPIPoolExecutor as Pool
>     p = Pool()
>     if p.is_worker():
>       exit()
>     l = list(range(100))
>     r = p.map(op, _grouper(10, l))
>     p.shutdown()
> ```
> 
> Like before though, the workers will only survive 1 pool and all subsequent code is master only

Yes, that seems to work for me, although I don't immediately understand why the workers don't die immediately when the `exit()` is called.  In any case, because the code is essentially serial (+ multithreading) I'm OK with the workers dying after the 1 pool is closed.

**Comment by Helveg** [comment] 2021-03-08 16:32
The problem is that I don't know of any "long jump" code patterns in python, unless you wrap all of the code that is supposed to be skipped in something, there's no way for me to say that the workers should "jump ahead" to the shutdown of the pool.

And yes, the workers WILL immediately die when exit is called :p

**Comment by bernstei** [comment] 2021-03-08 16:42
> 
> And yes, the workers WILL immediately die when exit is called :p

In that case, why is it working?  Why are the workers staying around long enough to run their mapped function calls?

**Comment by Helveg** [comment] 2021-03-08 16:50
Aha, on this line: `p = Pool()` they enter into the constructor, and because they are workers they are sent off to do the worker loop. The master exits out of that line and continues down the code. It receives instructions and sends those to the workers in their loop. Then when the pool is shut down the workers are released from their loop and also start continuing to read the lines below `p = Pool()`.

Among other things they will all start reading `map` instructions that they themselves have just already executed 😂 Clearly something that has to be prevented :) If you just put an `exit` for the workers after that line `p = Pool()` they exit after the pool shuts down.

**Comment by bernstei** [comment] 2021-03-08 16:56
OK, that makes sense.  Thanks.

**Comment by bernstei** [comment] 2021-03-08 17:36
I just checked, and I'm not actually getting any parallelism from `map()`.  Each call is being done by a different MPI task, but they wait for the previous one to finish.    I'll post a simple example in a minute,.

**Comment by bernstei** [comment] 2021-03-08 17:41
OK.  Here's a simplified source file which outputs from the task _when_ it starts. [test_zwembad.txt](https://github.com/Helveg/zwembad/files/6103145/test_zwembad.txt) The output I get looks like 
```
> mpirun -np 4 python3 test_zwembad.txt
using zwembad.MPIPoolExecutor
using zwembad.MPIPoolExecutor
using zwembad.MPIPoolExecutor
using zwembad.MPIPoolExecutor
1 op len(args) 1 1615225210.107522
[tin.nrl.navy.mil:95057] 3 more processes have sent help message help-mpi-btl-openib.txt / error in device init
[tin.nrl.navy.mil:95057] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
1 end of op len(args) 1
2 op len(args) 1 1615225220.120876
3 op len(args) 1 1615225230.1345966
2 end of op len(args) 1
1 op len(args) 1 1615225240.148129
3 end of op len(args) 1
```

You can see from the time stamps that it waits 10 seconds between start start of each task

**Comment by bernstei** [comment] 2021-03-08 19:18
I had to change the definition of map, because attempting to call `result()` hung the list comprehension loop until the task was complete, thus killing parallelism.
```
    def map(self, fn, *iterables):
        """
        Submits jobs for as long as all ``iterables`` provide values and places the
        results in a list. The iterables are consumed greedily.
        """
        # Submit all sets of parameters in the given iterables to the pool and collect
        # the results in a list.
        futures = [self.submit(fn, *args) for args in zip(*iterables)]
        l = [f.result() for f in futures]
        return l
```

**Comment by bernstei** [comment] 2021-03-08 19:53
I'm happy to close this issue with the "if worker: exit()" workaround, unless you want to keep it open until you add a cleaner approach.  The map parallelism problem is now described in issue #10

**Comment by Helveg** [comment] 2021-03-09 17:34
I hadn't seen your replies here before I dove in myself, your solution is correct 👍

**Closed as completed by Helveg** 2021-03-09 17:34 UTC

**Comment by Helveg** [comment] 2021-03-11 17:41
@bernstei since I can't "goto" the end of the pool, encapsulating statements like "if" or "with" are my only option, but for single use, would #9 be a more elegant and acceptable solution for you?
